import Image from "next/image";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <nav className='md:absolute right-10 top-5'>
          <Image
            src='/logo.png'
            alt='playsphere logo'
            height={200}
            width={200}
          />
        </nav>
        {children}
      </body>
    </html>
  );
}
